name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
