name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install packages
        run: npm install
      - name: Run Lint and prettier
        run: npm run lint:all
