name: Release

on:
  push:
    branches:
      - main
      - rc
      - beta

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install packages
        run: npm install
      - name: Run Lint and prettier
        run: npm run lint:all
  release:
    name: Versioning and publish
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
